pidev-web/src/main/java/tn/esprit/pidev/presentation/mbeans/PortfolioBean.java
package tn.esprit.pidev.presentation.mbeans;

import java.util.List;

import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;


import tn.esprit.pidev.entity.Portfolio;
import tn.esprit.pidev.service.PortfolioService;



@ManagedBean
@SessionScoped
public class PortfolioBean {
	
	private int id;
	private String type;
	private String category;
	
	private List<Portfolio> portfolios;
	private Integer portfolioIdToBeUpdated;
	static  Portfolio x;
	@EJB
	PortfolioService portfolioService;
	
	public void addEmploye() {
		System.out.println(portfolioService.getPortfolios());
		portfolioService.addPortfolio(new Portfolio(type,category));
	}
	
	public void supprimer(Integer employeId) {
		portfolioService.delete(employeId);
	}
	
	public void modifier(Portfolio employe) {
		this.setCategory(employe.getCategory());
		this.setType(employe.getType());
		this.setPortfolioIdToBeUpdated(employe.getId());
	}
	
	public void mettreAjourEmploye() {
		System.out.println(portfolioIdToBeUpdated);
		portfolioService.update(new Portfolio(type,category,portfolioIdToBeUpdated));
	}
	public String passage(Portfolio x){
		String navigateTo = "null";
		
		//employe = employeService.getEmployeByEmailAndPassword(login, password);((x.getType().equals("defensive"))||(x.getType().equals("aggressive")))
		if((x.getType().equals("defensive"))||(x.getType().equals("aggressive"))) {
			System.out.println("hello world");
			navigateTo="ContenuPortfolio?faces-redirect=true";
			
		}else {
			FacesContext.getCurrentInstance().addMessage("form:btn",new FacesMessage("bad credentials"));
		}
		return navigateTo;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getCategory() {
		return category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public List<Portfolio> getPortfolios() {
		return portfolios;
	}

	public void setPortfolios(List<Portfolio> portfolios) {
		this.portfolios = portfolios;
	}

	public Integer getPortfolioIdToBeUpdated() {
		return portfolioIdToBeUpdated;
	}

	public void setPortfolioIdToBeUpdated(Integer portfolioIdToBeUpdated) {
		this.portfolioIdToBeUpdated = portfolioIdToBeUpdated;
	}

	public PortfolioService getPortfolioService() {
		return portfolioService;
	}

	public void setPortfolioService(PortfolioService portfolioService) {
		this.portfolioService = portfolioService;
	}
	public List<Portfolio> getEmployes() {
		portfolios=portfolioService.getPortfolios();
		return portfolios;
	}

	
	
}

pidev-web/src/main/webapp/pages/admin/ContenuPortfolio.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"

	>

<ui:include src="../../header.xhtml" />
<body>
 <!-- Preloader Start -->
    <div id="preloader">
        <div class="circle"></div>
        <div class="left-door"></div>
        <div class="right-door"></div>
    </div>
    
    
 
<div id="aa" class="text-center" data-img-src="template/img/background-images/contact-page.jpg" >
	<h1>Add/Remove Option From Portfolio</h1>
		<h:form id="form">
		<div class="panel-body panel-body-table">

                                    <div class="table-responsive">
			<h:dataTable value="#{portfolioBean.employes}" var="portfolio" border="5" class="table table-bordered table-striped table-actions">
				<h:column>
					<f:facet name="header">
					 <span class="label label-info" style="font-size:15px"><h:outputText value="Type" /></span> 
						
					</f:facet>
					 <span class="label label-success" style="font-size:15px">  
					<h:outputText value="#{portfolio.type}" /></span>
				</h:column>

				<h:column>
					<f:facet name="header">
					<span class="label label-info" style="font-size:15px">
						<h:outputText value="Category" /></span>
					</f:facet>
					<span class="label label-danger" style="font-size:15px">
					<h:outputText value="#{portfolio.category}" /></span>
				</h:column>

				

				
				<h:column>
					<f:facet name="header">
					<span class="label label-info" style="font-size:15px">
						<h:outputText value="Action" /></span>
					</f:facet>
					<h:commandButton action="#{portfolioBean.supprimer(portfolio.id)}"
						value="Deleate" class="btn btn-warning btn-rounded btn-sm fa-times" />
					
					<h:commandButton action="#{portfolioBean.modifier(portfolio)}"
						value="Update" class="btn btn-default btn-rounded btn-sm"/>
				</h:column>

			</h:dataTable>
			</div>
			</div>
			<br />
			<br />
			<br />
			<br />


			<h:panelGrid columns="2">

				<h:outputText value="T y p e " class="form-control label label-warning"  />
				<h:inputText value="#{portfolioBean.type}" class="form-control"/>

				<h:outputText value="C a t e g o r y" class="form-control label label-warning" />
				
                                              
				<h:inputText value="#{portfolioBean.category}" class="form-control"/>
				                                          
                                         

<br/>
<br/>
                                                                      
                                    
                                  
									
                                     <!--    <label class="col-md-6 col-xs-12 control-label">* Category:</label>
                                        <div class="col-md-6 col-xs-12">    
	                                    <span class="input-group-addon"><span class="fa fa-pencil"></span></span>
                                                <h:inputText value="#{portfolioBean.category}" />
                                                                                   
                                          </div> -->
                                     
                                  
				
			
<div class="col-md-12">
				<h:commandButton action="#{portfolioBean.addEmploye()}"
					value="Add portfolio" class="mdl-button  mdl-button--accent"/>
					</div>
					
					<br/>
					<div class="col-md-12">
				<h:commandButton action="#{portfolioBean.mettreAjourEmploye()}"
					value="Confirm update" class="mdl-button  mdl-button--accent"/>
					</div>

			</h:panelGrid>
		
</h:form>
</div>


	
	<!-- Portfolio Projects Area End -->
	
	<!-- Testimonial Area Start -->
    
	<!-- Testimonial Area End -->
	
	<!-- Pricing Table Area Start -->
    
	<!-- Pricing Table Area End -->
	
	<!-- Brands Area Start -->
	
	<!-- Brands Area End -->
	
	<!-- Blog Area Start -->
    
	<!-- Blog Area End -->
	
	<!-- Contact Area Start -->
    
	<!-- Contact Area End -->
	

	
	
	
	<!-- Portfolio Details Modal Start -->
	<div class="modal fade" id="portfolioDetailsModal" tabindex="-1" role="dialog" aria-labelledby="portfolioDetailsModal">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"></span></button>
				<div id="portfolioDetails">
                    <div class="portfolio-popup mdl-card mdl-shadow--2dp">
                        <div class="mdl-card__title">
                            <div class="mfp-img">
                                <img class="mfp-img img-responsive" src="img/portfolio-images/portfolio-img-1.jpg" alt=""></img>
                            </div>
                        </div>
                        <div class="mdl-card__supporting-text">
                            <h2 class="mfp-title">Lorem ipsum sit amet dolor</h2>
                            <div class="mfp-description">
                                <p>Estibulum id, eleifend justo vel bibendum sapien massa ac turpis faucibus orci luctus non, consectetuer lobortis quis, varius in, purus. Integer ultrices posuere cubilia. Estibulum id, eleifend justo vel bibendum sapien massa ac turpis faucibus orci luctus non, consectetuer lobortis quis, varius in, purus. Integer ultrices posuere cubilia.</p><p>Estibulum id, eleifend justo vel bibendum sapien massa ac turpis faucibus orci luctus non, consectetuer lobortis quis, varius in, purus. Integer ultrices posuere cubilia. Estibulum id, eleifend justo vel bibendum sapien massa ac turpis faucibus orci luctus non, consectetuer lobortis quis, varius in, purus. Integer ultrices posuere cubilia.</p>
                            </div>
                        </div>
                        <div class="mdl-card__actions mdl-card--border clearfix">
                            <div class="mfp-link">
                                <a href="#" class="mfp-link mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--raised mdl-button--accent">Live Preview</a>
                            </div>
                            <div class="mfp-social">
                                <ul>
                                    <li><a href="#" class="mdl-button mdl-js-button mdl-js-ripple-effect"><i class="fa fa-facebook"></i></a></li>
                                    <li><a href="#" class="mdl-button mdl-js-button mdl-js-ripple-effect"><i class="fa fa-twitter"></i></a></li>
                                    <li><a href="#" class="mdl-button mdl-js-button mdl-js-ripple-effect"><i class="fa fa-google-plus"></i></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
				</div>
			</div>
		</div>
	</div>
	<!-- Portfolio Details Modal End -->
	
	<!-- Popup Navigation Area Start -->
	<div id="popupNav">
        <button id="popupNavButton" class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--primary mdl-button--fab mdl-shadow--4dp">
            <i class="add">+</i>
        </button>

        <ul class="popupNavMenu animateScroll2 mdl-menu mdl-menu--top-right mdl-js-menu mdl-js-ripple-effect" data-mdl-for="popupNavButton">
          <li><a href="#header"><span class="mdl-shadow--2dp">Home</span><i class="fa fa-home mdl-shadow--4dp"></i></a></li>
          <li><a href="#services"><span class="mdl-shadow--2dp">Our Services</span><i class="fa fa-cog mdl-shadow--4dp"></i></a></li>
          <li><a href="#about"><span class="mdl-shadow--2dp">About Us</span><i class="fa fa-info mdl-shadow--4dp"></i></a></li>
          <li><a href="#portfolio"><span class="mdl-shadow--2dp">Portfolio</span><i class="fa fa-photo mdl-shadow--4dp"></i></a></li>
          <li><a href="#pricingTable"><span class="mdl-shadow--2dp">Our Pricing</span><i class="fa fa-dollar mdl-shadow--4dp"></i></a></li>
          <li><a href="#contact"><span class="mdl-shadow--2dp">Contact Us</span><i class="fa fa-envelope mdl-shadow--4dp"></i></a></li>
          <li><a href="#footer"><span class="mdl-shadow--2dp">Footer</span><i class="fa fa-arrow-down mdl-shadow--4dp"></i></a></li>
        </ul>
	</div>
	<!-- Popup Navigation Area End -->
		
    <!-- Color Switcher Start -->
    <div id="open-switcher">
        <i class="fa fa-paint-brush"></i>
    </div>
    <div id="close-switcher">
        <i class="fa fa-times"></i>
    </div>
   
    <!-- Color Cwitcher End -->

	<!-- ====jQuery Core JavaScript==== -->
	<script src="template/js/jquery-2.2.2.min.js"></script>

	<!-- ====Bootstrap Core JavaScript==== -->
	<script src="template/js/bootstrap.min.js"></script>

	<!-- ====Material Design Lite Core JavaScript==== -->
	<script src="template/js/material.min.js"></script>

	<!-- ====animateScroll JavaScript==== -->
	<script src="template/js/animatescroll.min.js"></script>
	
    <!-- ====Google MAPS API JavaScript==== -->
	<script src="https://maps.googleapis.com/maps/api/js"></script>
    
    <!-- ====Twitter Fetcher JavaScript==== -->
    <script src="template/js/twitterFetcher_min.js"></script>
	
    <!-- ====jQuery Validation JavaScript==== -->
    <script src="template/js/jquery.validate.min.js"></script>
	
    <!-- ====Owl Carousel JavaScript==== -->
    <script src="template/js/owl.carousel.min.js"></script>
	
    <!-- ====Waypoints JavaScript==== -->
    <script src="template/js/jquery.waypoints.min.js"></script>
	
    <!-- ====Isotope JavaScript==== -->
    <script src="template/js/isotope-docs.min.js"></script>
	
    <!-- ====jQuery CounterUp JavaScript==== -->
    <script src="template/js/jquery.counterup.min.js"></script>
	
    <!-- ====Magnific Popup JavaScript==== -->
    <script src="template/js/jquery.magnific-popup.min.js"></script>
	
    <!-- ====Youtube Background JavaScript==== -->
    <script src="template/js/jquery.tubular.1.0.js"></script>
	
    <!-- ====jQuery Direction Aware Hover JavaScript==== -->
    <script src="template/js/jquery.directional-hover.min.js"></script>
	
    <!-- ====RetinaJS JavaScript==== -->
    <script src="template/js/retina.min.js"></script>

	<!-- ====BizLinks Core JavaScript==== -->
	<script src="template/js/mainc4ca.js?1"></script>

	<!-- ====Color Switcher JavaScript==== -->
    <script src="template/js/color-switcher.js"></script>
   
</body>
<ui:include src="../../footer.xhtml" />
</html>

<!-- Mirrored from www.themelooks.com/demo/bizlinks/html/version-2/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 09 Oct 2016 14:17:14 GMT -->

pidev-web/src/main/webapp/pages/admin/ajouterContrat.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="/template/template.xhtml">


	<ui:define name="content">
		<h1>Ajouter un Contrat a un employer</h1>
		<h:form id="form">
			<table>
				<tr>
					<td><h:outputText value="Employe" /></td>
					<td><h:selectOneMenu value="#{contratBean.selectedEmployeId}">
							<f:selectItems value="#{contratBean.employes}" var="employe"
								itemValue="#{employe.id}"
								itemLabel="#{employe.nom} #{employe.prenom}" />
						</h:selectOneMenu></td>
				</tr>

				<tr>
					<td><h:outputText value="Date Debut" /></td>
					<td><h:inputText id="date" value="#{contratBean.date}">
							<f:convertDateTime pattern="dd-MM-yyyy" />
						</h:inputText></td>
					<td><h:message for="date" style="color:red" /></td>
				</tr>

				<tr>
					<td><h:outputText value="Salaire" /></td>
					<td><h:inputText value="#{contratBean.salaire}" /></td>
				</tr>

				<tr>
					<td><h:outputText value="Type Contrat" /></td>
					<td><h:inputText value="#{contratBean.typeContrat}" /></td>
				</tr>
				<tr>
					<td></td>
					<td>
					<h:commandButton action="#{contratBean.ajoutContrat()}"
					value="Ajouter Contrat" />
					</td>
				</tr>
				
			</table>
		</h:form>
	</ui:define>

</ui:composition>

pidev-web/src/main/webapp/pages/admin/gererEmploye.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="/template/template.xhtml">

	
	<ui:define name="content">
	<h1>Gerer les employers</h1>
		<h:form id="form">
			<h:dataTable value="#{portfolioBean.portfolios}" var="pf" border="1">
				<h:column>
					<f:facet name="header">
						<h:outputText value="type" />
					</f:facet>
					<h:outputText value="#{pf.type}" />
				</h:column>

				<h:column>
					<f:facet name="header">
						<h:outputText value="category" />
					</f:facet>
					<h:outputText value="#{pf.category}" />
				</h:column>

				

				
				<h:column>
					<f:facet name="header">
						<h:outputText value="Action" />
					</f:facet>
					<h:commandButton action="#{portfolioBean.supprimer(portfolio.id)}"
						value="Supprimer" />
					<h:commandButton action="#{portfolioBean.modifier(portfolio)}"
						value="Modifier" />
				</h:column>

			</h:dataTable>


			<h:panelGrid columns="2">

				<h:outputText value="type " />
				<h:inputText value="#{portfolioBean.type}" />

				<h:outputText value="category" />
				<h:inputSecret value="#{portfolioBean.category}" />

				
			

				<h:commandButton action="#{portfolioBean.addEmploye()}"
					value="Ajouter portfolio" />
				<h:commandButton action="#{portfolioBean.mettreAjourEmploye()}"
					value="Mettre a jour portfolio" />

			</h:panelGrid>
		</h:form>

	</ui:define>

</ui:composition>

pidev-web/src/main/webapp/pages/admin/welcome.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="/template/template.xhtml">

	<ui:define name="title">Choisir une fonctionnalité:  </ui:define><br />
	<ui:define name="content">
		<h:link outcome="/pages/admin/gererEmploye" value="Gerer les employes" />
		<br />
		<br />
		<h:link outcome="/pages/admin/ajouterContrat" value="Ajouter un contrat pour un employe existant" />
	</ui:define>



</ui:composition>
