pidev-web/src/main/java/tn/esprit/pidev/presentation/mbeans/ClaimsBean.java
package tn.esprit.pidev.presentation.mbeans;

import java.io.IOException;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;

import tn.esprit.pidev.entity.Reclamation;
import tn.esprit.pidev.services.ReclamationService;
import yahoofinance.Stock;
import yahoofinance.YahooFinance;
import yahoofinance.histquotes.HistoricalQuote;
import yahoofinance.histquotes.Interval;

@ManagedBean
@SessionScoped
public class ClaimsBean {
private String content;
private String response;
private String Status;
private Date claimDate;
private String type;
private String option;
private List<Reclamation> claims;
private Reclamation claim;
private Integer claimIdtoBeRespond;

private List<HistoricalQuote>shares;
private HistoricalQuote share=new HistoricalQuote();
private String symbole;


@EJB
ReclamationService claimService;
@PostConstruct
public void init(){
	claimDate=new Date();
	Status="not treated";
	response=" ";

	
}
public void searchforStocksbysymbol(String period, int num) {
	Stock stock = null;
	if (period.equals("none") && num == 0) {
		try {
			
			stock = YahooFinance.get(symbole, true);
			
		} catch (IOException ex) {

			System.out.println("gs");
		}
	} else {
		try {
			Calendar from = Calendar.getInstance();
			Calendar to = Calendar.getInstance();
			if (period.equals("Month")) {
				from.add(Calendar.MONTH, -num);
				stock = YahooFinance.get(symbole, from, to, Interval.MONTHLY);
			} else if (period.equals("Year")) {
				from.add(Calendar.YEAR, -num);
				stock = YahooFinance.get(symbole, from, to, Interval.WEEKLY);
			} else if (period.equals("Day")) {
				from.add(Calendar.DAY_OF_YEAR, -num);
				stock = YahooFinance.get(symbole, from, to, Interval.DAILY);
			}

		} catch (IOException ex) {
		
			System.out.println("hh");
		}
	}

	shares = new ArrayList<HistoricalQuote>();
	try {
		shares = stock.getHistory();

	} catch (IOException e) {

		e.printStackTrace();
	}
	System.out.println("hhdjdjdjjd");
	for (HistoricalQuote historicalQuote : shares) {
		System.out.println("symbol " + historicalQuote.getSymbol());
		System.out.println("adj close" + historicalQuote.getAdjClose());
		System.out.println("close " + historicalQuote.getClose());
		System.out.println("date " + historicalQuote.getDate().getTime());
		System.out.println("high" + historicalQuote.getHigh());
		System.out.println("low " + historicalQuote.getLow());
		System.out.println("open " + historicalQuote.getOpen());
		System.out.println("volume " + historicalQuote.getVolume());

	}

}

public void getstocks(){
	searchforStocksbysymbol("none", 0);
	FacesContext.getCurrentInstance().getPartialViewContext().getRenderIds().add("formyahoo:dt");
	
}
public void addClaim(){
	
	SimpleDateFormat Format=new SimpleDateFormat();
	System.out.println("date"+ Format.format(claimDate));
	Reclamation claim=new Reclamation(option,content, claimDate, Status);
	claimService.ajoutReclamation(claim);
	
}
public void Respond(Reclamation claim){
this.setContent(claim.getContent());
this.setClaimIdtoBeRespond(claim.getId());
	
}
public void repond1(){
	claimService.updateReclamation(new Reclamation(claimIdtoBeRespond, content, claimDate, response, "treated", option));
}
public Reclamation rechercheParId(int id) {
	return claimService.getReclamationById(id);

}

public List<Reclamation> getAllClaims(){
	claims=claimService.getReclamation();
	return claims;
}
public void deleteClaim(Integer claimId){
	claimService.deleteReclamationById(claimId); 
	
}

public String getContent() {
	return content;
}
public void setContent(String content) {
	this.content = content;
}
public String getResponse() {
	return response;
}
public void setResponse(String response) {
	this.response = response;
}
public String getStatus() {
	return Status;
}
public void setStatus(String status) {
	Status = status;
}
public Date getClaimDate() {
	return claimDate;
}
public void setClaimDate(Date claimDate) {
	this.claimDate = claimDate;
}
public String getType() {
	return type;
}
public void setType(String type) {
	this.type = type;
}
public String getOption() {
	return option;
}
public void setOption(String option) {
	this.option = option;
}
public List<Reclamation> getClaims() {
	return claims;
}
public void setClaims(List<Reclamation> claims) {
	this.claims = claims;
}
public Reclamation getClaim() {
	return claim;
}
public void setClaim(Reclamation claim) {
	this.claim = claim;
}
public Integer getClaimIdtoBeRespond() {
	return claimIdtoBeRespond;
}
public void setClaimIdtoBeRespond(Integer claimIdtoBeRespond) {
	this.claimIdtoBeRespond = claimIdtoBeRespond;
}


public void SearchByType(String status){
	claims.addAll(claimService.rech(status));
}
public List<HistoricalQuote> getShares() {
	return shares;
}
public void setShares(List<HistoricalQuote> shares) {
	this.shares = shares;
}

public String getSymbole() {
	return symbole;
}
public void setSymbole(String symbole) {
	this.symbole = symbole;
}
public void getValues(HistoricalQuote stock){
stock.setLow(stock.getLow());
stock.setHigh(stock.getHigh());
stock.setClose(stock.getClose());
stock.setOpen(stock.getOpen());
System.out.println("ttttttttttt");
}
public String calculeAverage(){
	HistoricalQuote stock=new HistoricalQuote();
	String average="";
	Float a=Float.parseFloat(stock.getHigh().toString());
	Float b=Float.parseFloat(stock.getClose().toString());
	Float c=Float.parseFloat(stock.getLow().toString());
	Float d=Float.parseFloat(stock.getOpen().toString());
	Float e=(a*b*c*d)/4;
 return average=e.toString();
	
}
/**
 * @return the share
 */
public HistoricalQuote getShare() {
	return share;
}
/**
 * @param share the share to set
 */
public void setShare(HistoricalQuote share) {
	this.share = share;
}



}

pidev-web/src/main/java/tn/esprit/pidev/presentation/mbeans/LoginBean.java
package tn.esprit.pidev.presentation.mbeans;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.annotation.Resource;
import javax.ejb.EJB;
import javax.ejb.SessionContext;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;

import tn.esprit.pidev.entity.Type;
import tn.esprit.pidev.entity.User;
import tn.esprit.pidev.services.UserService;

import org.primefaces.event.SelectEvent;

@SessionScoped
@ManagedBean
public class LoginBean {
	private String first_name;
	private String last_name;
	private String tel;
	private String address;
	private String mail;
	private String pwd;
	private boolean active=true;
	private User user;
	private boolean loggedIn;
	private Date date_of_birth;
	private List<User> users;
	private Integer UserIdToBeUpdated;
	private Type type;
	private String search;

	@EJB
	UserService userService;
	public void onDateSelect(SelectEvent event) {
        FacesContext facesContext = FacesContext.getCurrentInstance();
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Date Selected", format.format(event.getObject())));
    }
     
    

	
	public String doLogin(){
		String navigateTo="null";
		user=userService.getUserByLoginPwd(mail, pwd);
		if(user!=null && user.getType()==Type.Trader){
			navigateTo="/MyProfile?faces-redirect=true";
			loggedIn=true;
		}else if (user!=null && user.getType()==Type.Admin) {
			navigateTo = "/usersTable?faces-redirect=true"; 
			loggedIn = true;
		
		}else {
			FacesContext.getCurrentInstance().addMessage("form:btn", new FacesMessage("bad credentials"));
		}
		return navigateTo;
		
	}
	public 	String doLogout(){
		 FacesContext.getCurrentInstance().getExternalContext().invalidateSession();
		 return"/template1?faces-recdirect=true";
		
	}
	public String getFirst_name() {
		return first_name;
	}
	public void setFirst_name(String first_name) {
		this.first_name = first_name;
	}
	public String getLast_name() {
		return last_name;
	}
	public void setLast_name(String last_name) {
		this.last_name = last_name;
	}
	public String getTel() {
		return tel;
	}
	public void setTel(String tel) {
		this.tel = tel;
	}
	public String getAddress() {
		return address;
	}
	public void setAddress(String address) {
		this.address = address;
	}
	public String getMail() {
		return mail;
	}
	public void setMail(String mail) {
		this.mail = mail;
	}
	public String getPwd() {
		return pwd;
	}
	public void setPwd(String pwd) {
		this.pwd = pwd;
	}
	public boolean isActive() {
		return active;
	}
	public void setActive(boolean active) {
		this.active = active;
	}
	public User getUser() {
		return user;
	}
	public void setUser(User user) {
		this.user = user;
	}
	public boolean isLoggedIn() {
		return loggedIn;
	}
	public void setLoggedIn(boolean loggedIn) {
		this.loggedIn = loggedIn;
	}
	public Date getDate_of_birth() {
		return date_of_birth;
	}
	public void setDate_of_birth(Date date_of_birth) {
		this.date_of_birth = date_of_birth;
	}
	public UserService getUserService() {
		return userService;
	}
	public void setUserService(UserService userService) {
		this.userService = userService;
	}
	
	
	public Integer getUserIdToBeUpdated() {
		return UserIdToBeUpdated;
	}




	public void setUserIdToBeUpdated(Integer userIdToBeUpdated) {
		UserIdToBeUpdated = userIdToBeUpdated;
	}




	public void addUser(){
		SimpleDateFormat simpleFormat=new SimpleDateFormat("dd-MM-yyyy");
		System.out.println("date:"+ simpleFormat.format(date_of_birth));

		userService.ajouterUser(new User(first_name, last_name, tel, address, mail, pwd,date_of_birth));
	}




	public List<User> getUsers() {
		return users;
	}




	public String getSearch() {
		return search;
	}




	public void setSearch(String search) {
		this.search = search;
	}




	public void setUsers(List<User> users) {
		this.users = users;
	}
public List<User> getTraders(){
	users=userService.getUsers();
	return users;
}
public void supprimer(Integer UserId){
	userService.deleteUserByid(UserId);
}
public void modifier(User user){
	this.setFirst_name(user.getFirst_name());
	this.setLast_name(user.getLast_name());
	this.setDate_of_birth(user.getDate_of_birth());
	this.setMail(user.getMail());
	this.setPwd(user.getPwd());
	this.setTel(user.getTel());
	this.setAddress(user.getAddress());
	this.setUserIdToBeUpdated(user.getId());
	
}
public void mettreAjourUser(){
userService.UpdateUser(new User(UserIdToBeUpdated, first_name, last_name, tel, address, mail, pwd, date_of_birth,type));
}




public Type getType() {
	return type;
}




public void setType(Type type) {
	this.type = type;
}
public void handleKeyEvenet(){
	users.clear();
	users=new ArrayList<>();
	if(search==null || search.equals("")){
		search="";
		users=userService.getUsers();
	}else
			users=userService.rech(search);
		
		
	}
	

public void baneUser(int id){
	userService.blockUser(id);
}
}

pidev-web/src/main/java/tn/esprit/pidev/presentation/mbeans/OptionBean.java
package tn.esprit.pidev.presentation.mbeans;

import java.util.Date;
import java.util.List;

import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.naming.NamingException;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;

import tn.esprit.pidev.presentation.mbeans.PortfolioBean;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;

import tn.esprit.pidev.entity.Portfolio;
import tn.esprit.pidev.entity.StockOption;
import tn.esprit.pidev.service.PortfolioService;
import tn.esprit.pidev.service.StockOptionService;



@ManagedBean
@SessionScoped
public class OptionBean {
	
	private int id;
	private String contact_name;
	private float ask;
	private float bid;
	private float strike;
	private float volume;
	
	private List<StockOption> options;
	private List<StockOption> options1;
	private List<Portfolio> portfolios;
	private Integer optionIdToBeUpdated;
	private Integer selectedOptionId;
	public List<StockOption> getOptions1() {
		return options1;
	}

	public void setOptions1(List<StockOption> options1) {
		this.options1 = options1;
	}

	public List<Portfolio> getPortfolios() {
		return portfolios;
	}

	public void setPortfolios(List<Portfolio> portfolios) {
		this.portfolios = portfolios;
	}

	public Integer getSelectedOptionId() {
		return selectedOptionId;
	}

	public void setSelectedOptionId(Integer selectedOptionId) {
		this.selectedOptionId = selectedOptionId;
	}
	@EJB
	PortfolioService optionService;
	
	public void init() {
		
		//options = optionService.getAllOption1(2);
	}
	
	public void addOption() {
		//System.out.println(portfolioService.getPortfolios());
		StockOption selectedEmploye = new StockOption();
		//selectedEmploye.setId(selectedOptionId);
		System.out.println(PortfolioBean.x.getId()+"hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh");
		//selectedEmploye.setPortfolio(PortfolioBean.x);
		//optionService.affecterOptionPortfolio(2,11);
		
		//.setEmploye(selectedEmploye);
		//int i = employeService.ajouterContrat(contrat);
		//employeService.affecterContratAEmploye(i, selectedEmployeId);
	}
	
	public void supprimer(StockOption o) {
		optionService.desaffecterOptionPortfolio(PortfolioBean.x.getId(), o.getId());
	}
	
	/*public void modifier(Portfolio employe) {
		this.setCategory(employe.getCategory());
		this.setType(employe.getType());
		this.setPortfolioIdToBeUpdated(employe.getId());
	}
	
	public void mettreAjourEmploye() {
		System.out.println(portfolioIdToBeUpdated);
		portfolioService.update(new Portfolio(type,category,portfolioIdToBeUpdated));
	}
	public String passage(Portfolio x){
		String navigateTo = "null";
		
		//employe = employeService.getEmployeByEmailAndPassword(login, password);((x.getType().equals("defensive"))||(x.getType().equals("aggressive")))
		if((x.getType().equals("defensive"))||(x.getType().equals("aggressive"))) {
			System.out.println("hello world");
			navigateTo="ContenuPortfolio?faces-redirect=true";
			
		}else {
			FacesContext.getCurrentInstance().addMessage("form:btn",new FacesMessage("bad credentials"));
		}
		return navigateTo;
	}*/

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	
	public String getContact_name() {
		return contact_name;
	}

	public void setContact_name(String contact_name) {
		this.contact_name = contact_name;
	}

	public float getAsk() {
		return ask;
	}

	public void setAsk(float ask) {
		this.ask = ask;
	}

	public float getBid() {
		return bid;
	}

	public void setBid(float bid) {
		this.bid = bid;
	}

	public float getStrike() {
		return strike;
	}

	public void setStrike(float strike) {
		this.strike = strike;
	}

	public float getVolume() {
		return volume;
	}

	public void setVolume(float volume) {
		this.volume = volume;
	}

	public List<StockOption> getOptions() {
		return options;
	}

	public void setOptions(List<StockOption> options) {
		this.options = options;
	}

	public Integer getOptionIdToBeUpdated() {
		return optionIdToBeUpdated;
	}

	public void setOptionIdToBeUpdated(Integer optionIdToBeUpdated) {
		this.optionIdToBeUpdated = optionIdToBeUpdated;
	}

	

	public PortfolioService getOptionService() {
		return optionService;
	}

	public void setOptionService(PortfolioService optionService) {
		this.optionService = optionService;
	}

	public List<StockOption> getOs() {
		options=optionService.getAllOption(2);
		System.out.println(PortfolioBean.x.getId()+"hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh");
		return options;
	}
	public List<StockOption> 	getCbox(){
	//ObservableList<StockOption> combojobs = FXCollections.observableArrayList();
    List<StockOption> jobs = optionService.getAllOption1(2); //getall //getall
    System.out.println(jobs);
   /* for (StockOption job : jobs) {
    	if((job.getPortfolio()==null)){
    		
        options1.add(job);
   
    }}*/
    System.out.println(PortfolioBean.x.getId()+"hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh");
   return jobs;
    
} 

	
	
}

pidev-web/src/main/webapp/AllClaims.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html">

<ui:include src="header.xhtml" />

<h:head>
<h:outputStylesheet library="css" name="table.css"  />
</h:head>


<body>
 <!-- Preloader Start -->
    <div id="preloader">
        <div class="circle"></div>
        <div class="left-door"></div>
        <div class="right-door"></div>
    </div>
    
	

	
	
	
	<!-- Portfolio Details Modal Start -->
	<div class="modal fade" id="portfolioDetailsModal" tabindex="-1" role="dialog" aria-labelledby="portfolioDetailsModal">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"></span></button>
				<div id="portfolioDetails">
                    <div class="portfolio-popup mdl-card mdl-shadow--2dp">
                        <div class="mdl-card__title">
                            <div class="mfp-img">
                                <img class="mfp-img img-responsive" src="img/portfolio-images/portfolio-img-1.jpg" alt=""></img>
                            </div>
                        </div>
                        <div class="mdl-card__supporting-text">
                            <h2 class="mfp-title">Lorem ipsum sit amet dolor</h2>
                            <div class="mfp-description">
                                <p>Estibulum id, eleifend justo vel bibendum sapien massa ac turpis faucibus orci luctus non, consectetuer lobortis quis, varius in, purus. Integer ultrices posuere cubilia. Estibulum id, eleifend justo vel bibendum sapien massa ac turpis faucibus orci luctus non, consectetuer lobortis quis, varius in, purus. Integer ultrices posuere cubilia.</p><p>Estibulum id, eleifend justo vel bibendum sapien massa ac turpis faucibus orci luctus non, consectetuer lobortis quis, varius in, purus. Integer ultrices posuere cubilia. Estibulum id, eleifend justo vel bibendum sapien massa ac turpis faucibus orci luctus non, consectetuer lobortis quis, varius in, purus. Integer ultrices posuere cubilia.</p>
                            </div>
                        </div>
                        <div class="mdl-card__actions mdl-card--border clearfix">
                            <div class="mfp-link">
                                <a href="#" class="mfp-link mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--raised mdl-button--accent">Live Preview</a>
                            </div>
                            <div class="mfp-social">
                                <ul>
                                    <li><a href="#" class="mdl-button mdl-js-button mdl-js-ripple-effect"><i class="fa fa-facebook"></i></a></li>
                                    <li><a href="#" class="mdl-button mdl-js-button mdl-js-ripple-effect"><i class="fa fa-twitter"></i></a></li>
                                    <li><a href="#" class="mdl-button mdl-js-button mdl-js-ripple-effect"><i class="fa fa-google-plus"></i></a></li>
                                </ul>
                            </div>
                            
                        </div>
                    </div>
				</div>
			</div>
		</div>
	</div>
	<!-- Portfolio Details Modal End -->
	
	<!-- Popup Navigation Area Start -->
	<div id="popupNav">
        <button id="popupNavButton" class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--primary mdl-button--fab mdl-shadow--4dp">
            <i class="add">+</i>
        </button>

        <ul class="popupNavMenu animateScroll2 mdl-menu mdl-menu--top-right mdl-js-menu mdl-js-ripple-effect" data-mdl-for="popupNavButton">
          <li><a href="#header"><span class="mdl-shadow--2dp">Home</span><i class="fa fa-home mdl-shadow--4dp"></i></a></li>
          <li><a href="#services"><span class="mdl-shadow--2dp">Our Services</span><i class="fa fa-cog mdl-shadow--4dp"></i></a></li>
          <li><a href="#about"><span class="mdl-shadow--2dp">About Us</span><i class="fa fa-info mdl-shadow--4dp"></i></a></li>
          <li><a href="#portfolio"><span class="mdl-shadow--2dp">Portfolio</span><i class="fa fa-photo mdl-shadow--4dp"></i></a></li>
          <li><a href="#pricingTable"><span class="mdl-shadow--2dp">Our Pricing</span><i class="fa fa-dollar mdl-shadow--4dp"></i></a></li>
          <li><a href="#contact"><span class="mdl-shadow--2dp">Contact Us</span><i class="fa fa-envelope mdl-shadow--4dp"></i></a></li>
          <li><a href="#footer"><span class="mdl-shadow--2dp">Footer</span><i class="fa fa-arrow-down mdl-shadow--4dp"></i></a></li>
        </ul>
	</div>
	<!-- Popup Navigation Area End -->
		
    <!-- Color Switcher Start -->
    <div id="open-switcher">
        <i class="fa fa-paint-brush"></i>
    </div>
    <div id="close-switcher">
        <i class="fa fa-times"></i>
    </div>
   
    <!-- Color Cwitcher End -->

	<!-- ====jQuery Core JavaScript==== -->
	<script src="template/js/jquery-2.2.2.min.js"></script>

	<!-- ====Bootstrap Core JavaScript==== -->
	<script src="template/js/bootstrap.min.js"></script>

	<!-- ====Material Design Lite Core JavaScript==== -->
	<script src="template/js/material.min.js"></script>

	<!-- ====animateScroll JavaScript==== -->
	<script src="template/js/animatescroll.min.js"></script>
	
    <!-- ====Google MAPS API JavaScript==== -->
	<script src="https://maps.googleapis.com/maps/api/js"></script>
    
    <!-- ====Twitter Fetcher JavaScript==== -->
    <script src="template/js/twitterFetcher_min.js"></script>
	
    <!-- ====jQuery Validation JavaScript==== -->
    <script src="template/js/jquery.validate.min.js"></script>
	
    <!-- ====Owl Carousel JavaScript==== -->
    <script src="template/js/owl.carousel.min.js"></script>
	
    <!-- ====Waypoints JavaScript==== -->
    <script src="template/js/jquery.waypoints.min.js"></script>
	
    <!-- ====Isotope JavaScript==== -->
    <script src="template/js/isotope-docs.min.js"></script>
	
    <!-- ====jQuery CounterUp JavaScript==== -->
    <script src="template/js/jquery.counterup.min.js"></script>
	
    <!-- ====Magnific Popup JavaScript==== -->
    <script src="template/js/jquery.magnific-popup.min.js"></script>
	
    <!-- ====Youtube Background JavaScript==== -->
    <script src="template/js/jquery.tubular.1.0.js"></script>
	
    <!-- ====jQuery Direction Aware Hover JavaScript==== -->
    <script src="template/js/jquery.directional-hover.min.js"></script>
	
    <!-- ====RetinaJS JavaScript==== -->
    <script src="template/js/retina.min.js"></script>

	<!-- ====BizLinks Core JavaScript==== -->
	<script src="template/js/mainc4ca.js?1"></script>

	<!-- ====Color Switcher JavaScript==== -->
    <script src="template/js/color-switcher.js"></script>
    <div class="container">
			<div class="row">
				<div class="col-md-12">
				<div class="col-md-12 about-page-description">
						<div class="col-md-12 about-page-image">
    <h:form id="Form">
    
	<div class="mdl-textfield mdl-js-textfield">
	<h:inputText value="#{claimsBean.SearchByType(claimsBean.status)}" class="mdl-textfield__input" type="text" name="singupName" id="singupName"/> 
	<label class="mdl-textfield__label" for="singupName">search for trader</label>
	</div>
    
<h:dataTable value="#{claimsBean.allClaims}" var="claim" class="table table-bordred table-striped table-actions" >
<h:column> 
<f:facet name="header">
<h:outputText value="id" />
</f:facet>

<h:outputText value="#{claim.id}" />
</h:column>
<h:column> 
<f:facet name="header">
<h:outputText value="content" />
</f:facet>
<h:outputText value="#{claim.content}" />
</h:column>
<h:column>
<f:facet name="header">
<h:outputText value="Response" />
</f:facet>
<h:outputText value="#{claim.response}" />
</h:column>
<h:column>
<f:facet name="header">
<h:outputText value="Date of claim" />
</f:facet>
<h:outputText value="#{claim.claimDate}" />
</h:column>
<h:column>
<f:facet name="header">
<h:outputText value="Status" />
</f:facet>
<h:outputText value="#{claim.status}" />
</h:column>
<h:column>
<f:facet name="header">
<h:outputText value="share" />
</f:facet>
<h:outputText value="#{claim.option}" />
</h:column>
<h:column>
<f:facet name="header">
<h:outputText value="Delete" />
</f:facet>
<h:commandButton action="#{claimsBean.deleteClaim(claim.id)}" value="Delete"  class="singup-form-submit-btn mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent"/>
</h:column>
<h:column>
<f:facet name="header">
<h:outputText value="Answer" />
</f:facet>
<h:commandButton action="#{claimsBean.Respond(claim)}" value="Answer"  class="singup-form-submit-btn mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent"/>
</h:column>
</h:dataTable>
</h:form>
</div>
</div>
</div>
</div>
</div>
	<div class="modal-content">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"></span></button>
				<div class="signupForm">
					<div class="mdl-card mdl-shadow--2dp">
						
						<h:form id="ReponseForm">
						<div class="mdl-card__supporting-text">
							
							
								<div class="mdl-textfield mdl-js-textfield">
									<h:inputText value="#{claimsBean.content}" class="mdl-textfield__input" type="text" name="singupName" id="singupName"/>
									<label class="mdl-textfield__label" for="singupName">content</label>
								</div>
								<div class="mdl-textfield mdl-js-textfield">
									<h:inputText value="#{claimsBean.response}" class="mdl-textfield__input" type="text" name="singupUsername" id="singupUsername" placeholder="Response"/>
								<label class="mdl-textfield__label" for="singupUsername">Response</label>
								</div>
								  <div class="row">
                                <div class="col-md-12">
								<h:commandButton action="#{claimsBean.repond1()}" type="submit" class="login-form-submit-btn mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent" value="Send">
									
								</h:commandButton>
                                </div>
                            </div>
							
								</div> 
								
								</h:form>
									</div>
								</div>
								</div>
							
								

</body>
<ui:include src="footer.xhtml" />
</html>

<!-- Mirrored from www.themelooks.com/demo/bizlinks/html/version-2/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 09 Oct 2016 14:17:14 GMT -->